//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TestNetEnum.rc
//
#define IDS_LIC_TEXT                    1
#define IDS_CANCEL                      2
#define IDS_CB_DISABLED                 3
#define IDS_CB_DAILY                    4
#define IDS_CB_STARTUP                  5
#define IDS_CB_WEEKLY                   6
#define IDS_CB_MONTHLY                  7
#define IDS_SERVER_STATIC               8
#define IDS_FREQ_STATIC                 9
#define IDS_OK                          10
#define IDS_CFG_SLANG                   12
#define IDS_CFG_LLANG                   13
#define IDS_LANG_STATIC                 14
#define IDS_CFG_ILANG                   16
#define IDS_USER_STATIC                 19
#define IDS_PWD_STATIC                  20
#define IDS_MACHUSER_STATIC             49
#define IDS_MACHPWD_STATIC              50
#define IDS_MACH_PROCESSING             51
#define IDS_MACH_PASSED                 52
#define IDS_MACH_FAILED                 53
#define IDS_ERR_NO_SOURCE_SHARE         54
#define IDS_ERR_START_TASK_MGR          55
#define IDS_ERR_NO_INSTALLER            56
#define IDS_ERR_NO_INSTALL_TASK         57
#define IDS_INST_COMPLETE               58
#define IDS_INST_TOTAL_ATTEMPT          59
#define IDS_INST_TOTAL_PASS             60
#define IDS_INST_TOTAL_FAIL             61
#define IDS_NET_ID_LOCAL                62
#define IDS_NET_ID_NETWORK              63
#define IDS_NET_ID_DOMAIN               64
#define IDS_INSTALL                     65
#define IDS_LOCAL_SCAN                  66
#define IDS_SCAN                        67
#define IDS_NET_SCAN_START              68
#define IDS_NET_SCAN_DONE               69
#define IDS_NET_SCAN_CANCEL             70
#define IDS_INST_CANCEL                 71
#define IDS_CLOSE                       72
#define IDS_LIC_ACCEPT                  73
#define IDS_LIC_DLG_CAPTION             74
#define IDS_INST_DLG_CAPTION            75
#define IDS_INST_START                  76
#define IDS_INTRO_SCAN_INVITE           77
#define IDS_PLEASE_FILL_FORM            78
#define IDS_PLEASE_CHOOSE_MACH          79
#define IDS_PLEASE_FILL_FORM_CAP        80
#define IDS_PLEASE_CHOOSE_MACH_CAP      81
#define IDS_NO_MACH                     82
#define IDS_PRUNE_UNAVAIL               83
#define IDS_PRUNE_INCOMPAT              84
#define IDS_UNINSTALL                   85
#define IDS_UNINST_CANCELLED            86
#define IDS_ERR_NO_UNINSTALLER          87
#define IDS_UNINST_TOTAL_ATTEMPT        88
#define IDS_UNINST_TOTAL_PASS           89
#define IDS_UNINST_TOTAL_FAIL           90
#define IDS_UNINST_COMPLETE             91
#define IDS_UNINST_START                92
#define IDS_NO_PROXY                    93
#define IDS_IE_PROXY                    94
#define IDS_MANUAL_PROXY                95
#define IDS_PROXY_COMBO_STATIC          96
#define IDS_PROXY_SERVER_STATIC         97
#define IDS_MACHDOMAIN_STATIC           98
#define IDS_PROXY_PORT_STATIC           99
#define IDS_ACCTID_STATIC               100
#define IDD_NETVIEW                     101
#define IDD_NET_INSTALL                 101
#define IDS_MACHLOCAL_STATIC            101
#define IDB_SYSLIST_LOGO                102
#define IDI_INSTALLER16                 103
#define IDI_INSTALLER32                 104
#define IDD_LIC_LANG                    106
#define IDR_RAW_TEXT_LIC                107
#define IDC_NETTREE                     1000
#define IDC_INSTALL                     1001
#define IDC_CANCEL                      1002
#define IDC_LOG                         1003
#define IDC_CLOSE                       1004
#define IDC_SCAN_NET                    1005
#define IDC_MACH_USER_STATIC            1006
#define IDC_MACH_USER_EDIT              1007
#define IDC_MACH_PWD_STATIC             1008
#define IDC_MACH_PWD_EDIT               1009
#define IDC_SYSLIST_USER_STATIC         1010
#define IDC_LANG_STATIC                 1010
#define IDC_SYSLIST_USER_EDIT           1011
#define IDC_LANG_COMBO                  1011
#define IDC_SYSLIST_PWD_STATIC          1012
#define IDC_SYSLIST_PWD_EDIT            1013
#define IDC_SYSLIST_SERVER_STATIC       1014
#define IDC_SYSLIST_SERVER_EDIT         1015
#define IDC_SYSLIST_FREQ_STATIC         1016
#define IDC_FREQ_COMBO                  1017
#define IDC_LIC_ACCEPT                  1017
#define IDC_LOCAL_CHECK                 1018
#define IDC_LIC_CANCEL                  1018
#define IDC_LIC_LOGO                    1019
#define IDC_PRUNE_UNAVAIL_CHECK         1019
#define IDC_PRUNE_INCOMPAT_CHECK        1020
#define IDC_PROXY_COMBO                 1021
#define IDC_LIC_TEXT                    1022
#define IDC_PROXY_SERVER_EDIT           1022
#define IDC_UNINSTALL                   1023
#define IDC_PROXY_SERVER_STATIC         1024
#define IDC_LIC_VERSION_STATIC          1024
#define IDC_PROXY_COMBO_STATIC          1025
#define IDC_VERSION_STATIC              1026
#define IDC_MACH_DOMAIN_EDIT            1027
#define IDC_MACH_DOMAIN_STATIC          1028
#define IDC_SYSLIST_ACCTID_EDIT         1029
#define IDC_SYSLIST_ACCTID_STATIC       1030
#define IDC_PROXY_PORT_EDIT             1031
#define IDC_PROXY_PORT_STATIC           1032
#define IDC_MACH_LOCAL_CHECK            1033

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
