#!/bin/sh

rm -rf /Library/Receipts/SCA_Install*.pkg

BASE_PKG_DIR=`dirname $PACKAGE_PATH`
CONF_PATH="$BASE_PKG_DIR/config"

SCA_CONFIG="/Applications/Syslist Companion Agent/SCAConfig.app/Contents/MacOS/SCAConfig"

if test -f $CONF_PATH ; then
    "$SCA_CONFIG" -config "$CONF_PATH" -no_ui || exit 1;
elif test -z $COMMAND_LINE_INSTALL ; then
	"$SCA_CONFIG" -install || exit 1 ;
fi

"/Applications/Syslist Companion Agent/SCATimeEx"& 

exit 0